[package]
name = "pascal_piramid"
version = "0.1.0"
authors = ["Jorge Hevia <jmhev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
